### ISSUE TITLE
CCK Debug, does not show triggers that are off by default but then toggled on

### ISSUE THREAD

**Issue by NovaVoidHowl** [kafeijao/Kafe_CVR_Mods#11]
I have some trigger areas that are toggled off by default on load in then get enabled when toggling on some armor. (trigger is to switch the visor on/off)  
But it appears that the trigger area that gets toggled does not render in the debug view  

![image](https://user-images.githubusercontent.com/31048789/200118463-50a9e1a7-91d2-4352-aa95-8a36dfbbd74c.png)
![image](https://user-images.githubusercontent.com/31048789/200118519-93691da2-d9a2-4a8c-90eb-7b0d13198d6b.png)

**Comment by kafeijao** [comment]
This should be fixed on https://github.com/kafeijao/Kafe_CVR_Mods/releases/tag/r50

Re-open otherwise please
