### ISSUE TITLE
[CCK.Debugger] Visualizer GameObjects should copy parents layer.

### ISSUE THREAD

**Issue by NotAKidOnSteam** [kafeijao/Kafe_CVR_Mods#15]
The visualizer GameObject should copy the parent GameObjects layer.
This is to keep consistency in Mirrors & Cameras.

![image](https://user-images.githubusercontent.com/37721153/209202585-787c9eb4-b640-4f0b-a6d1-00badc59e799.png)

**Comment by kafeijao** [comment]
This should be fixed on https://github.com/kafeijao/Kafe_CVR_Mods/releases/tag/r50

Re-open otherwise please
