### ISSUE TITLE
[CCK.Debugger] Sphere visualizer radius is off by 2x.

### ISSUE THREAD

**Issue by NotAKidOnSteam** [kafeijao/Kafe_CVR_Mods#16]
The sphere collider visualizers are off by 2x. 
Radius is the measurement between the center and the edge of a circle, so to scale the 3D spheres properly the radius must be doubled.

![debugger](https://user-images.githubusercontent.com/37721153/209203441-2a37051b-b434-4313-889d-d6deb5412df5.png)

**Comment by kafeijao** [comment]
Fixed in 482c6270d5ff11c8c758f807dc256652e63c5f70
It's still on the cohtml branch, I'll try to merge to main when I can.

**Comment by kafeijao** [comment]
This should be fixed on https://github.com/kafeijao/Kafe_CVR_Mods/releases/tag/r50

Re-open otherwise please
