### ISSUE TITLE
[CCK.Debugger] Use "UI Internal" layer (layer 16) for UI

### ISSUE THREAD

**Issue by NotAKidOnSteam** [kafeijao/Kafe_CVR_Mods#18]
CCK.Debugger UI is affected by postprocessing and can be overrendered by the world. 

It would make sense to place it on the UI Internal layer alongside the QM and MM to prevent it.

![image](https://user-images.githubusercontent.com/37721153/210929097-34f621f6-cfbc-4618-a399-3f3d57aec2f7.png)

**Comment by kafeijao** [comment]
This should be fixed on https://github.com/kafeijao/Kafe_CVR_Mods/releases/tag/r50

Re-open otherwise please
