### ISSUE TITLE
[FreedomFingers] Gesture toggle doesn't disable gestures (2023-06-26 - R171)

### ISSUE THREAD

**Issue by AstroDogeDX** [kafeijao/Kafe_CVR_Mods#37]
Pressing the 'toggle gestures' button doesn't disable gestures, despite the UI message saying so.

**Comment by AstroDogeDX** [comment]
Okay, it does work so long as 'Enable Gestures During Finger Tracking' is disabled in the menu, however the notification is inverted. Gestures don't lock when toggled either.

**Comment by kafeijao** [comment]
Should be fixed in the latest update :3
