### ISSUE TITLE
Great mod

### ISSUE THREAD

**Issue by anoni111** [kafeijao/Kafe_CVR_Mods#41]
This is an incredible job, very well designed, you have a great level of programming, I would like to ask you if you could add a small update of the version of libsm64 unity that has been outdated for years, not even audio, nobody has been responsible for updating that and I think it has great potential, thanks in advance

**Comment by kafeijao** [comment]
I'm sorry, but the code base has diverged a lot. Also most of my stuff is hacks to allow it to work in ChilloutVR and not really relevant anywhere else.

**Comment by anoni111** [comment]
Okay, Thanks for reply
