### ISSUE TITLE
[OSC] Bug Report - "/input/Voice" causes Spam Mic Toggling

### ISSUE THREAD

**Issue by Kin-kay** [kafeijao/Kafe_CVR_Mods#42]
`client.send_message("/input/Voice",bool(True))` One of these causes Mic to spam toggle until `client.send_message("/input/Voice",bool(False))` is sent or game is shut down. Tested slowing down amount sent, sent 1 every `time.sleep(100)`, but still spammed Mic. Can try to record video if needed.

Using most recent pythonosc.

**Comment by kafeijao** [comment]
Hello @Kin-kay, thanks for the report!

I fixed the issue and updated the `.dll` on https://github.com/kafeijao/Kafe_CVR_Mods/releases/tag/r57
Let me know if it fixed it for you.

This fix will be bundled on the next update (should be when the next experimental becomes stable)

**Comment by Kin-kay** [comment]
It worked! Thank you.
