### ISSUE TITLE
[ChatBox] Does not use nameplate shaders for proper billboarding.

### ISSUE THREAD

**Issue by NotAKidOnSteam** [kafeijao/Kafe_CVR_Mods#45]
The ChatBox does not use the nameplate shaders for billboarding. This is most noticeable on Desktop.
![image](https://github.com/kafeijao/Kafe_CVR_Mods/assets/37721153/fa85777c-a05a-48f9-a4ed-5caa3c94149e)

**Comment by kafeijao** [comment]
Implemented on ce2f7e01c3c69e3c38a1316d0b2edbaf38433939
