### ISSUE TITLE
[OSC] OSC breaks parameter Stream on bbc-cbt

### ISSUE THREAD

**Issue by UgabugaTDK** [kafeijao/Kafe_CVR_Mods#46]
I don't know all of them, but it's at least breaking Headset On Head

**Comment by kafeijao** [comment]
Atm I'm only keeping up to date with the stable branch. Sometimes I do a pre-release for experimental.
If I try to keep up with all the branches I will go insane x)

I'd suggest trying the experimental compatible pre-release: https://github.com/kafeijao/Kafe_CVR_Mods/releases/tag/r66

If that one doesn't work, you'll have wait wait for that branch to me merged to stable. (I might poke it when it goes to experimental, but can't promise).
