### ISSUE TITLE
The Clapper: configurable clapping gestures and ability to disable entirely.

### ISSUE THREAD

**Issue by hanetzer** [kafeijao/Kafe_CVR_Mods#51]
Simple request, I think. Playing chess with piracy and have accidentally clapped the board and
had to rejoin (thankfully saves state). The ability to disable it entirely would be nice.

Also, my default neutral irl hand position when using my index controllers is recognized as
hand open/-1, so it'd be nice to be able to chose the gesture chosen to prevent accidental
activation (doing finger gun left and rock and roll right requires conscious effort for the most
part), with it defaulting to 'open/open' to maintain compat for existing users without this complaint.

Actually, would it be possible to have the mod also have an option to 'prevent clapping friends
props' like it does for avatars?

**Comment by kafeijao** [comment]
I've been pretty busy lately, whenever I get some free time I can take a look into it 🙏

**Comment by hanetzer** [comment]
that's fine. I've half a mind to set up a dev vm because doing c# on linux is ass at best lmao.
you accept prs?

**Comment by kafeijao** [comment]
I probably won't make a release until the next stable, because I have pending changes from the experimental updates, and I rather not maintain 2 diff releases if not necessary

I do take PRs if you want to take a jab at it go for it. Although I'm a bit picky so I might edit it after

**Comment by hanetzer** [comment]
that's fine :+1: will see what I can do.

**Comment by kafeijao** [comment]
I've submit an update for publishing on CVRMG, meanwhile if you want to test it, you can grab it from https://github.com/kafeijao/Kafe_CVR_Mods/releases/latest
