### ISSUE TITLE
[CCK.Debugger] Menu object pickup

### ISSUE THREAD

**Issue by NotAKidOnSteam** [kafeijao/Kafe_CVR_Mods#6]
We definitely need a way to pick up and adjust the menu in-world without having to drop it in place each time.

Possibly a lock function to go along with it to prevent accidental pickups while testing gestures.

**Comment by kafeijao** [comment]
Added in https://github.com/kafeijao/Kafe_CVR_Mods/commit/3fd688f44bdfe7a82483143d9b0eadcb28b80a94
