### ISSUE TITLE
[CCK.Debugger] Button to return menu to QM

### ISSUE THREAD

**Issue by NotAKidOnSteam** [kafeijao/Kafe_CVR_Mods#7]
If I place the menu somewhere and forget about it, I'd like to be able to quickly return it to myself without having to look for and unpin it.

Possibly if I walk too far away from it?

**Comment by kafeijao** [comment]
Added in https://github.com/kafeijao/Kafe_CVR_Mods/commit/3fd688f44bdfe7a82483143d9b0eadcb28b80a94

I opted to create buttons on the QM menu where the pin/hud buttons would be, if the menu is more than 0.5m away from the QM original position and the menu is either pinned to world or to the hud, the buttons will show up.
